Update Singularity

diff --git a/containers/amrex/Singularity b/containers/amrex/Singularity
--- a/containers/amrex/Singularity
+++ b/containers/amrex/Singularity
@@ -7,17 +7,32 @@ Include: yum
 %help
 This is a container to run AMREX binarie on SKL machine. just type ./amrex.img and it should run
 
-%post
+%setup
+	#Create a working directory 
+        mkdir -p $SINGULARITY_ROOTFS/tempdir
+        if [ ! -x "$SINGULARITY_ROOTFS/tempdir" ]; then
+           echo "failed to create tempdir directory..."
+           exit 1
+        fi
+	
+	wget https://github.com/Smahane/Intel-HPC-Container/blob/master/containers/amrex/Nyx3d.intel.MPI.OMP.SKLAVX512.ex
+	    wget https://github.com/Smahane/Intel-HPC-Container/blob/master/containers/amrex/inputs
+	
+	    cp -rf Nyx3d.intel.MPI.OMP.SKLAVX512.ex $SINGULARITY_ROOTFS/tempdir
+	    cp -rf inputs $SINGULARITY_ROOTFS/tempdir   
+        if [ "$(ls -A $SINGULARITY_ROOTFS/tempdir/)" ]; then
+                   echo "Files are copies here $SINGULARITY_ROOTFS/tempdir"
+                   ls $SINGULARITY_ROOTFS/tempdir/
+        fi
 
-        #get binaries and input files
+                chmod -R 777 $SINGULARITY_ROOTFS/tempdir/*
+
+        exit 0
 	
+	
+%post
 	yum install wget -y
-        wget https://github.com/Smahane/Intel-HPC-Container/blob/master/containers/amrex/Nyx3d.intel.MPI.OMP.SKLAVX512.ex
-	wget https://github.com/Smahane/Intel-HPC-Container/blob/master/containers/amrex/inputs
-	
-	chmod 777 Nyx3d.intel.MPI.OMP.SKLAVX512.ex
-	chmod 777 inputs
-		
+       		
 	#installing runtime libs for virtual machines
         rpm --import https://yum.repos.intel.com/2018/setup/RPM-GPG-KEY-intel-psxe-runtime-2018
 	rpm -Uhv https://yum.repos.intel.com/2018/setup/intel-psxe-runtime-2018-reposetup-1-0.noarch.rpm
@@ -33,6 +48,8 @@ This is a container to run AMREX binarie on SKL machine. just type ./amrex.img a
 %runscript 
         echo "This is what happens when you run the container..."
 	
+	cd $SINGULARITY_ROOTFS/tempdir/
+	pwd
 	source /opt/intel/psxe_runtime/linux/bin/psxevars.sh
 	ls -l Nyx3d.intel.MPI.OMP.SKLAVX512.ex
 	result="Nyx3d.intel.MPI.OMP.SKLAVX512.log"
