Update Singularity

diff --git a/containers/amrex/Singularity b/containers/amrex/Singularity
--- a/containers/amrex/Singularity
+++ b/containers/amrex/Singularity
@@ -7,6 +7,13 @@ Include: yum
 %help
 This is a container to run AMREX binarie on SKL machine. just type ./amrex.img and it should run
 
+%setup
+        #Create a working directory 
+        mkdir -p $SINGULARITY_ROOTFS/tempdir
+        if [ ! -x "$SINGULARITY_ROOTFS/tempdir" ]; then
+           echo "failed to create tempdir directory..."
+           exit 1
+        fi
 %post
 
         #get binaries and input files
@@ -15,11 +22,13 @@ This is a container to run AMREX binarie on SKL machine. just type ./amrex.img a
         wget https://github.com/Smahane/Intel-HPC-Container/blob/master/containers/amrex/Nyx3d.intel.MPI.OMP.SKLAVX512.ex
 	wget https://github.com/Smahane/Intel-HPC-Container/blob/master/containers/amrex/inputs
 	
-	#cp -rf Nyx3d.intel.MPI.OMP.SKLAVX512.ex $SINGULARITY_ROOTFS/tempdir
-	#cp -rf inputs $SINGULARITY_ROOTFS/tempdir
+	chmod +x Nyx3d.intel.MPI.OMP.SKLAVX512.ex
+	chmod +x inputs
+	cp -rf Nyx3d.intel.MPI.OMP.SKLAVX512.ex $SINGULARITY_ROOTFS/tempdir
+	cp -rf inputs $SINGULARITY_ROOTFS/tempdir
 	
 	#installing runtime libs for virtual machines
-    rpm --import https://yum.repos.intel.com/2018/setup/RPM-GPG-KEY-intel-psxe-runtime-2018
+        rpm --import https://yum.repos.intel.com/2018/setup/RPM-GPG-KEY-intel-psxe-runtime-2018
 	rpm -Uhv https://yum.repos.intel.com/2018/setup/intel-psxe-runtime-2018-reposetup-1-0.noarch.rpm
 	yum install intel-psxe-runtime -y
 
@@ -32,7 +41,7 @@ This is a container to run AMREX binarie on SKL machine. just type ./amrex.img a
 	
 %runscript 
         echo "This is what happens when you run the container..."
-	
+	cd $SINGULARITY_ROOTFS/tempdir/
 	source /opt/intel/psxe_runtime/linux/bin/psxevars.sh
 	chmod +x Nyx3d.intel.MPI.OMP.SKLAVX512.ex
 	
